# Pakai PHP 8.2 + Apache
FROM php:8.2-apache

# Copy semua file project ke server
COPY . /var/www/html/

# Install cURL (wajib untuk OpenRouter)
RUN docker-php-ext-install curl

# Buka port 80 supaya bisa diakses di browser
EXPOSE 80
